[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mlops"
version = "0.1.0"
description = "A monorepo MLOps platform for PySpark and MLflow."
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["src"]